### PR TITLE
Test using fail in subset for custom message

### PR DESCRIPTION
**Pull request by zostay**

### CODE REVIEW

**Comment by zoffixznet** [comment]
Would it be possible to change this test to check the actual content of the custom message is correct? The current `dies-ok` version takes the `1 is not even` string as test description; not the content of the death to check against. For those purposes, there's [`throws-like`](https://docs.perl6.org/language/testing#index-entry-throws-like):

```perl6
throws-like { fail "foo" }, Exception, :message<foo>,
    'failure gave correct custom message';
```

**Comment by zostay** [comment]
Oh... duh... yeah, I'll fix it.

**Comment by zoffixznet** [comment]
Also, you forgot to adjust the `plan` at the top of the file :smile_cat:

**Comment by zostay** [comment]
Fixed the plan and using `throws-like` now. Thx for the review.

**Comment by zoffixznet** [comment]
Thanks a lot.

**Pull request merged**
