### PR TITLE
Bug 129862

### PR DESCRIPTION
**Pull request by tbrowder**
Added tests for issue RT #129862. Also divided table tests into two groups for better tracking.

### CODE REVIEW

**Comment by zoffixznet** [comment]
Can we please use [the fudge preprocessor](https://github.com/perl6/roast/blob/master/README#L22) for TODO skips, instead of a handrolled thing. 

Also, it'd be better to include more references (RT tickets, commits, PR links) for stuff like `after planned table pod fixes`. If the person promising that work doesn't come through, that will make for a very confusing comment in the roast.

Lastly, I see you mention *warning* on unaligned table rows. Can we make a more concrete decision: they're either allowed and there's no warning or they're forbidden and we throw an exception. 

Thanks.

**Comment by tbrowder** [comment]
On Fri, Oct 14, 2016 at 5:33 AM, Zoffix Znet <notifications@github.com> wrote:
> Can we please use the fudge preprocessor for TODO skips, instead of a
> handrolled thing.

Okay, wasn't aware of it.

> Also, it'd be better to include more references (RT tickets, commits, PR
> links) for stuff like after planned table pod fixes. If the person promising
> that work doesn't come through, that will make for a very confusing comment
> in the roast.

Agree.

> Lastly, I see you mention warning on unaligned table rows. Can we make a
> more concrete decision: they're either allowed and there's no warning or
> they're forbidden and we throw an exception.

Roger: it will be an exception, hopefully with a warning of the problem.

Changes to the PR coming...;

**Comment by tbrowder** [comment]
On Fri, Oct 14, 2016 at 5:55 AM, Tom Browder <tom.browder@gmail.com> wrote:
> On Fri, Oct 14, 2016 at 5:33 AM, Zoffix Znet <notifications@github.com> wrote:
>> Can we please use the fudge preprocessor for TODO skips, instead of a
>> handrolled thing.
>
> Okay, wasn't aware of it.

Ah, I remember it looking at it when I needed to skip tests--clear as
mud to me, but I'll see what I can do...looking for complete
examples...

**Comment by zoffixznet** [comment]
[Here's](https://github.com/perl6/roast/blob/master/S12-enums/thorough.t#L114) one.

The `#?rakudo todo 'reason'` TODOs the next nest that follows. `#?rakudo todo 3 'reason'` TODOs 3 next tests that follow.

If it has trouble figuring out what to fudge, you can also wrap stuff in a block and explicitly tell it how many tests are inside the block with [`#?DOES`](https://github.com/perl6/roast/blob/master/S12-enums/thorough.t#L22)

**Comment by tbrowder** [comment]
On Fri, Oct 14, 2016 at 7:57 AM, Zoffix Znet <notifications@github.com> wrote:
> Here's one.
>
> The #?rakudo todo 'reason' TODOs the next nest that follows. #?rakudo todo 3
> 'reason' TODOs 3 next tests that follow.
...

Thanks--very helpful!  I was just looking for fudge (slapping my
face...dummy!!).

**Comment by zoffixznet** [comment]
And the test files with a fudge in them need to be run through the fudger. From a rakudo checkout, you can run them with `make t/spec/some-file.t`. Speaking of which, any *new files* added to roast also need to be listed in [t/spectest.data](https://github.com/rakudo/rakudo/blob/b08ef9666e32358291bfcab8d323e13984c24a2d/t/spectest.data)

**Comment by tbrowder** [comment]
On Fri, Oct 14, 2016 at 8:20 AM, Zoffix Znet <notifications@github.com> wrote:
> And the test files with a fudge in them need to be run through the fudger.
> From a rakudo checkout, you can run them with make t/spec/some-file.t.
> Speaking of which, any new files added to roast also need to be listed in
> t/spectest.data

K.

**Comment by zoffixznet** [comment]
Spotting another thing: throughout the roast we use explicit `plan`s instead of `done-testing`.

Let me know when this is ready for merge.

**Comment by tbrowder** [comment]
On Fri, Oct 14, 2016 at 11:35 AM, Zoffix Znet <notifications@github.com> wrote:
> Spotting another thing: throughout the roast we use explicit plans instead
> of done-testing.
>
> Let me know when this is ready for merge.

Argh!  I thought I had discovered the Holy Grail...I'll change if you insist...

**Comment by tbrowder** [comment]
On Fri, Oct 14, 2016 at 11:37 AM, Tom Browder <tom.browder@gmail.com> wrote:
> On Fri, Oct 14, 2016 at 11:35 AM, Zoffix Znet <notifications@github.com> wrote:
>> Spotting another thing: throughout the roast we use explicit plans instead
>> of done-testing.
>>
>> Let me know when this is ready for merge.

Okay, I think it's ready: I've checked the two test files (one regular
and one fudged).  But do I have to add the fudged file, too? Or is all
that generated automatically in the complete test (which I haven't
done)?

**Comment by zoffixznet** [comment]
Thanks a lot!

**Pull request merged**
