### PR TITLE
Spectest for rakudo/rakudo/issues/3137

### PR DESCRIPTION
**Pull request by dumarchie**
Added spectest requested in rakudo/rakudo/pull/3139

### CODE REVIEW

**Comment by AlexDaniel** [comment]
This PR introduces 44 commits where only 2 are useful, and 42 were rebased by mistake. Please fix it before we can merge it.

**Comment by dumarchie** [comment]
I guess I used the wrong approach for pulling upstream changes into my fork. Let me figure out how to fix this.

**Comment by dumarchie** [comment]
@AlexDaniel Removed the irrelevant commits

**Comment by AlexDaniel** [comment]
@dumarchie, thank you!

**Pull request merged**
