### PR TITLE
More tests for combinations, including pathological cases

### PR DESCRIPTION
**Pull request by skids**

### CODE REVIEW

**Comment by skids** [comment]
To be merged after rakudo PR#732

**Comment by moritz** [comment]
Why do you compare .perl output in those tests, instead of just is-deeply? This looks like an anti-pattern to me.

**Comment by skids** [comment]
Mainly just because that is what the pre-existing code did.  Might predate is-deeply.

**Comment by zoffixznet** [comment]
Thanks. There were merge conflicts so I manually added these in https://github.com/perl6/roast/commit/1424793070962b78a9b3d366a808cb89ed27b1ed

**Pull request closed without merging**
