### PR TITLE
Skip test on NetBSD

### PR DESCRIPTION
**Pull request by stmuk**

### CODE REVIEW

**Comment by coke** [comment]
Please include a reference to an RT when fudging  tickets

**Comment by FROGGS** [comment]
What does `PR lib/49240` mean?

**Comment by stmuk** [comment]
It's a NetBSD library bug reference see
http://mail-index.netbsd.org/netbsd-bugs/2014/10/01/msg038454.html

On 21 March 2015 at 16:33, Tobias Leich <notifications@github.com> wrote:

> What does PR lib/49240 mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/roast/pull/54#issuecomment-84387827>.
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by usev6** [comment]
The problem can be found in RT #85750 (though a bit hidden in a later comment).

I fiddled a bit with the fudged test and added some references: https://github.com/perl6/roast/commit/8ae0b90b42

**Comment by stmuk** [comment]
I've created a new RT#124147: pow edge cases with rakudo-moar on NetBSD and changed the code to point to that (which itself points to  RT #85750).

Although there is relevant discussion about this issue in RT #85750 I believe that ticket itself (test failures on OpenBSD) can be closed since I saw a PASS on this platform yesterday.

**Pull request merged**
