### PR TITLE
A test for #130211

### PR DESCRIPTION
**Pull request by Altai-man**
Related to https://github.com/rakudo/rakudo/pull/957. Closes https://rt.perl.org/Public/Bug/Display.html?id=130211.

I just wrote checking of reverse-ordered role names to be independent from exact message.

### CODE REVIEW

**Comment by zoffixznet** [comment]
This test is a bit flimsy, since regular words in the message may contain letters 'C' and 'R'. Also, I don't think the Perl 6 Language should dictate in which order implementations must list the roles in this message.

I'd suggest you name the roles something more specific, like `R-RT130211` and `C-RT130211`, and simply check for presence of both in the message, instead of testing a specific order, so `message` would be something like:

```perl6
:message{ .contains('R-RT130211') and .contains('C-RT130211') }
```

**Comment by Altai-man** [comment]
Indeed, your approach is much better.

**Comment by zoffixznet** [comment]
> I get 255 error on my machine, so don't merge it yet.

That's because you put a space between `:message` and `{`

**Comment by Altai-man** [comment]
I'll squash latest commits now...

**Comment by zoffixznet** [comment]
Thanks a lot.

**Comment by Altai-man** [comment]
Oh, I'm late. Never mind then.

**Pull request merged**
